language: node_js
node_js:
- 4
- 6
- 8
- 9
after_success:
- npm install -g istanbul
- npm install coveralls
- istanbul cover node_modules/.bin/_mocha --report lcovonly -- -R spec
- ./node_modules/.bin/coveralls < ./coverage/lcov.info
- rm -rf ./coverage
deploy:
  provider: npm
  email: florian.reinhart@gmail.com
  api_key:
    secure: Hbtlm2kXLhrLIQMSpyMnioBaBhI31xJzbj5WguXzVU26DLNJeprTJnNBQwjPt5F99b5PMQiOEq7vIZB2DqY+PF3Gz3nxEnFHmT67FSLYkaibSyU13bt9BsUOIQg6d5yt0h13ZF86+kRNx65P7p4aM5P4Vj7v/xZjCwRQr2VIKTA=
  on:
    tags: true
